services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_job_board
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_network
    depends_on:
      - laravel_job_board_db
      - redis
  
  # Database service 
  laravel_job_board_db:
    image: mysql:8.0
    container_name: laravel_job_board_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - laravel_network

  # Redis service    
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    container_name: laravel_job_board_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: laravel_job_board_nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local