name: Deploy Laravel-Job Board to Development

on:
  push:
    branches:
     - development

jobs:
  deploy-development:
    name: Deploy to Development Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer Dependencies
        run: composer install -q --optimize-autoloader --no-interaction --prefer-dist --no-ansi --no-scripts --no-progress
      
      - name: Install Node.js Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM Packages
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Synchronize files to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}

      - name: Run Remote Deployment Script/Artisan Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.TARGET }}
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize


