name: Deploy Laravel (Development)

on:
  push:
    branches:
      - development

jobs:
  deploy-development:
    name: Deploy to Development Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer Dependencies Locally
        run: composer install --no-interaction --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install NPM Packages
        run: npm ci

      - name: Build Frontend Assets
        run: npm run build

      - name: Sync Files to Development Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: |
            .git*
            .env
            node_modules/**
            vendor/**
            storage/*.key
            tests
            .github/**
          ARGS: "-rltgoDzvO --no-perms"

      - name: Run Remote Artisan and Composer
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.TARGET }}

            # Install dependencies (with dev dependencies)
            composer install --no-interaction --prefer-dist

            # Migrate database
            php artisan migrate --force

            # Clear caches
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan cache:clear

            # Rebuild caches
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Create storage link
            php artisan storage:link || true

            # Optimize framework bootstrap files
            php artisan optimize